#!/usr/bin/env bash
#Commenter

if [ -e "school" ]
then
	  echo "school file exists"
	    if [ -s "holbertonschool" ]
		      then
			    echo "school file is not empty"
		    else
			    echo "school file is empty"
		 
			   
			   
if [ -f "school" ]
then
	echo "school is a regular file"
else
	 echo "school file does not exist"
fi
